TARGET = absolute leapyear p passfail grade grade2 posZeroNeg bigLetter one2Ten one2Tensum multiply ascii star

all : $(TARGET)

absolute : $@
leapyear : $@
p : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2Tensum : $@
multiply : $@
ascii : $@
star : $@

clean : 
	rm $(TARGET)