TARGET = enumExample unionExample dynamicAllocation filedescriptor filePointer strcat charPointerOperation hellostr sumMatrixFunc2 sumMatrixFunc sumArrayFunc swapFunction arrayCompare arrayAssignment voidPointer functionPointer p swap selection bubble qsort pointerconp endian pointer2

all : $(TARGET)
enumExample : $@
unionExample : $@
dynamicAllocation : $@
filedescriptor : $@
filePointer : $@
strcat : $@
charPointerOperation : $@
hellostr : $@
sumMatrixFunc2 : $@
sumMatrixFunc : $@
sumArrayFunc : $@
swapFunction : $@
arrayCompare : $@
arrayAssignment : $@
voidPointer : $@
functionPointer : $@
p :$@
swap : $@
selection : $@
bubble : $@ 
qsort : $@
pointerconp : $@
endian : $@
pointer2 : $@

clean : 
	rm $(TARGET)