TARGET = p swap selection bubble qsort pointerconp endian pointer2

all : $(TARGET)
p :$@
swap : $@
selection : $@
bubble : $@ 
qsort : $@
pointerconp : $@
endian : $@
pointer2 : $@

clean : 
	rm $(TARGET)