TARGET = infinit limit celsius2fahr fahr2celsius

all : infinit limit fahr2celsius celsius2fahr

infinit : infinit.c
	cc -o infinit infinit.c
limit : $@
fahr2celsius : $@
celsius2fahr : $@


clean : 
	rm $(TARGET)
