TARGET = infinit limit celsius2fahr fahr2celsius charNumber

all : $(TARGET)

infinit : infinit.c
	cc -o infinit infinit.c
limit : $@
fahr2celsius : $@
celsius2fahr : $@
charNumber : $@

clean : 
	rm $(TARGET)
