TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2

all : $(TARGET)

infinit : infinit.c
	cc -o infinit infinit.c
limit : $@
fahr2celsius : $@
celsius2fahr : $@
charNumber : $@
triangle : $@
triangle2 : $@

clean : 
	rm $(TARGET)
