TARGET = infinit limit celsius2fahr fahr2celsius charNumber triangle triangle2 arithmethics increment literal genderRatio compare practice sizeof oddeven fourbit

all : $(TARGET)

infinit : infinit.c
	cc -o infinit infinit.c
limit : $@
fahr2celsius : $@
celsius2fahr : $@
charNumber : $@
triangle : $@
triangle2 : $@
arithmethics : $@
increment : $@
literal : $@
practice : $@
genderRatio : $@
compare : $@
sizeof: $@
oddeven: $@
fourbit: $@

clean : 
	rm $(TARGET)
