TARGET = absolute leapyear p passfail grade grade2 posZeroNeg bigLetter one2Ten one2Tensum multiply ascii star one2TenWhile randomTwoint staticLocalVariable functionSum returnValue power

all : $(TARGET)

absolute : $@
leapyear : $@
p : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2Tensum : $@
multiply : $@
ascii : $@
star : $@
one2TenWhile : $@
randomTwoint : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power : $@

clean : 
	rm $(TARGET)