TARGET = absolute leapyear p passfail grade grade2 posZeroNeg bigLetter one2Ten one2Tensum multiply ascii star one2TenWhile randomTwoint staticLocalVariable functionSum returnValue power dice sumArray sumMatrix findMax findValue scoreGrade proscore average2022Temp baseball

all : $(TARGET)

absolute : $@
leapyear : $@
p : $@
passfail : $@
grade : $@
grade2 : $@
posZeroNeg : $@
bigLetter : $@
one2Ten : $@
one2Tensum : $@
multiply : $@
ascii : $@
star : $@
one2TenWhile : $@
randomTwoint : $@
staticLocalVariable : $@
functionSum : $@
returnValue : $@
power : $@
dice : $@
sumArray : $@
sumMatrix : $@
findMax : $@
findValue : $@
scoreGrade : $@
proscore : $@
average2022Temp : $@
baseball : $@


clean : 
	rm $(TARGET)